### ISSUE TITLE
Current install script points at beta plugin store

### ISSUE THREAD

**Issue by rhossack** [SteamDeckHomebrew/decky-loader#104]
The beta plugin store has no plugins. Just an example.

**Comment by TrainDoctor** [comment]
> The beta plugin store has no plugins. Just an example.

This is intentional. If you want to install the older version, you can use:
``curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/legacy/dist/install_release.sh | sh``.
I will update the README to reflect this.

**Comment by TrainDoctor** [comment]
> > The beta plugin store has no plugins. Just an example.
> 
> This is intentional. If you want to install the older version, you can use: `curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/legacy/dist/install_release.sh | sh`. I will update the README to reflect this.

I have changed the install script for users to use the legacy installer.
If users wish to have preview/test the React update, they can use:
``curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_prerelease.sh | sh``

**Comment by different55** [comment]
Heads up, the website documentation isn't yet updated and still points users at the beta store

**Comment by TrainDoctor** [comment]
> Heads up, the website documentation isn't yet updated and still points users at the beta store

This is now intentional.

**Comment by different55** [comment]
What's the intended intention behind that?

**Comment by botatooo** [comment]
The legacy ("non-beta") store, referred to as such because the beta subdomain is stable and is used in the latest builds, does not support the workflows used to upload plugins in the [SteamDeckHomebrew/decky-plugin-database](https://github.com/SteamDeckHomebrew/decky-plugin-database) repository. See https://github.com/SteamDeckHomebrew/decky-plugin-store/compare/legacy...main for the difference between the current (beta) store and the legacy one.
