### ISSUE TITLE
read-only filesystem not working

### ISSUE THREAD

**Issue by irol765** [SteamDeckHomebrew/decky-loader#292]
**describe**
steamos-readonly disable fails after installing decky-loader or plugin
/usr is always readonly

**Reproduce**
1. Reinstall steamos
2. update system 3.3.3
3. Switch desktop mode
4. Install decky-loader
5. Switch back to game mode and upgrade decky-loader
6. Install flatpakupdater/TunnelDeck/Fantastic/vibrantDeck/PowerTools/Bluetooth
7. Switch desktop mode
8. Cancel the read-only mode steamos-readonly disable
9. cd /usr mkdir 123
10. error

**Expected Behavior**
[A clear and concise description of what you expect to happen. ]

**screenshot**
[If applicable, please add screenshots to help explain your problem. ]

**Version Information**
   - SteamOS version: 3.3.3 20221213.1
stable version

** Additional context **
Have you ever modified a read-only filesystem?
yes

**Comment by TrainDoctor** [comment]
Nothing decky or it's plugins do could effect the read only filesystem. This is by design. We also do not provide support for systems with modified RO filesystems.

**Comment by AAGaming00** [comment]
This would be caused by enabling OpenVPN support in TunnelDeck, you can work around this by disabling it's OpenVPN support before disabling read-only.Note that installing Decky on a Deck with a modified filesystem is completely unsupported, so expect issues.On Dec 20, 2022 9:09 AM, irol765 ***@***.***> wrote:
describe
steamos-readonly disable fails after installing decky-loader or plugin
/usr is always readonly
Reproduce
Steps to reproduce the behavior:
Reinstall steamosupdate system 3.3.3Switch desktop modeInstall decky-loaderSwitch back to game mode and upgrade decky-loaderInstall flatpakupdater/TunnelDeck/Fantastic/vibrantDeck/PowerTools/BluetoothSwitch desktop modeCancel the read-only mode steamos-readonly disablecd /usr mkdir 123error
Expected Behavior
[A clear and concise description of what you expect to happen. ]
screenshot
[If applicable, please add screenshots to help explain your problem. ]
Version Information
SteamOS version: 3.3.3 20221213.1
stable version
** Additional context **
Have you ever modified a read-only filesystem?
yes
