### ISSUE TITLE
Suggestion: Link to Repo from DeckUI

### ISSUE THREAD

**Issue by JohnnyBlocks** [SteamDeckHomebrew/decky-loader#294]
For plug-ins it would be neat to have a link to the repo instead of just an author name.

Is there vetting process for plugins or can anyone add them to the list?   I like to review the code before I add plugins.

**Comment by TrainDoctor** [comment]
> Is there vetting process for plugins or can anyone add them to the list? I like to review the code before I add plugins.

Yes there's an entire submission, review and testing process. Please see the [wiki](https://deckbrew.xyz/en/plugin-dev/review-and-testing) page covering the topic. Here's [the repository](https://github.com/SteamDeckHomebrew/decky-plugin-database) where all plugins are stored as a submodule.

**Comment by JohnnyBlocks** [comment]
Thanks for the confirmation.  

But yes a link to their repo on [this](https://plugins.deckbrew.xyz/) UI would be super nice.

**Comment by TrainDoctor** [comment]
> But yes a link to their repo on [this](https://plugins.deckbrew.xyz/) UI would be super nice.

The web page UI is legacy and will probably be dropped at some time in the future. @EMERALD0874 is working on a UI revamp to the current decky store UI and I'll ask them to add some considerations in to account for such a link.

**Comment by PartyWumpus** [comment]
> The web page UI is legacy and will probably be dropped at some time in the future

Would just like to say: I think it could be a good idea to keep the web version of the store alive in some form (probably with the nonfunctional download buttons removed and replaced with repo links or something). I've seen some users wanting to see what kind of plugins are available before they install decky and i'd imagine some might be put off by a github repo.

Not actually sure if anyone actually has used it though and not sure if that outweighs the number of people it's confused.

(Possibly a better idea to put this in #280, not sure? Sorry that this is a little off-topic from the issue raised.)

**Comment by AAGaming00** [comment]
Due to how the plugins are currently uploaded and stored, the plugin store backend has no way to tell what repo a plugin can be found at. It only knows the creator's name and the plugin's name, not the URL.On Dec 24, 2022 4:31 PM, Party Wumpus ***@***.***> wrote:

The web page UI is legacy and will probably be dropped at some time in the future

Would just like to say: I think it could be a good idea to keep the web version of the store alive in some form (probably with the nonfunctional download buttons removed and replaced with repo links or something). I've seen some users wanting to see what kind of plugins are available before they install decky and i'd imagine some might be put off by a github repo.
Not actually sure if anyone actually has used it though and not sure if that outweighs the number of people it's confused.
(Possibly a better idea to put this in #280, not sure? Sorry that this is a little off-topic from the issue raised.)

**Comment by JohnnyBlocks** [comment]
That is why it needs to be a feature request.   

The schema needs to be expanded.  User interface created.  Etc etc.  

It would be a huge quality/trust improvement for people looking at plugins.

**Comment by EMERALD0874** [comment]
During the store redesign in #343, I considered adding a repo link area for each plugin but decided it would create too much clutter as the entire URL would need to be shown for it to be effective (most people aren't going to review source code from the Deck itself).

As a compromise, there is now a note in the About tab that gives information on how to easily find the source code of plugins. Please feel free to reopen this issue if this isn't satisfactory. https://github.com/SteamDeckHomebrew/decky-loader/pull/343/commits/3e039cab82f093257fc968b566806beff0075e95
