### ISSUE TITLE
[BUG] Decky Loader Setting Itself to Pre-Release Update Branch and Plugins Stop Running

### ISSUE THREAD

**Issue by 2ndbest** [SteamDeckHomebrew/decky-loader#354]
### Please confirm

- [X] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

Decky Loader stops working seconds after launching steamdeck. It says it switched to pre release but most plugins stop working including the ability to to update, uninstall, or download anymore 

### Expected Behaviour

being able to use plugins

### SteamOS version

3.4.3 Stable

### Selected Update Channel

Stable

### Logs

[loader-backendlog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10529001/loader-backendlog.txt)

**Comment by zzdm360** [comment]
Encountering the same problem, less than 10 seconds after being in game mode all the plugin stops working 
Can't uninstall,reload or do anythings in decky settings and it switch by itself on "prerelease"
I can only enter in the powertools plugin, css loader is giving an error, animation changer shows everything in default, the plugin downloader is not working too


[loader-backendlog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10530072/loader-backendlog.txt)

**Comment by TrainDoctor** [comment]
It seems like the updater process is not working. Please backup your homebrew directory and then uninstall decky via the Desktop shortcut (this will not remove your plugins or configs) and then execute ``sudo rm -r /home/deck/homebrew`` (THIS WILL DELETE THEM, BACKUP HOMEBREW DIR BEFOREHAND!!!). Replace everything but the plugins directory into the new homebrew folder. Re-install your plugins one by one. Restart each time you install a plugin and see if anything changes. In order to grab logs for the entire process, run ``journalctl -u plugin_loader.service > loader-backend-testing.txt`` to grab the logs.
I have been unable to replicate this issue locally. Thanks.

**Comment by TrainDoctor** [comment]
This may be addressed when #373 is merged. Go ahead and give the binary from the PR a try and see if it helps. 👍

**Comment by TrainDoctor** [comment]
Now that #373 is merged, let me know if this issue has been fixed for you @2ndbest. Thanks.

**Comment by 2ndbest** [comment]
its working now, thank you!

**Comment by TrainDoctor** [comment]
Considering this fixed now. Huzzah.

**Comment by coldfirefusion001** [comment]
Hello, Excuse my dumbness, but how do I incorporate this solution into my steam deck?

**Comment by PartyWumpus** [comment]
> Hello, Excuse my dumbness, but how do I incorporate this solution into my steam deck?

@coldfirefusion001 You'd just update decky from the deck UI or via the installer. But this issue is from feburary, so you'd probably already have the version with this fixed.
