### ISSUE TITLE
[Request] Allow toggle to force toast notification even if all plugins are already updated 

### ISSUE THREAD

**Issue by ttang4299** [SteamDeckHomebrew/decky-loader#425]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Seeing the toast notification say that no new plugin updates are available is much more reassuring than getting no toast notification at all, because then I at least know that the loader was successful in checking for any updates. Otherwise, I end up pressing the "check for updates" button several times, and I get frustrated when there is actually an update and I see the same toast notification several times over because of how many times I've pressed the button.

Additionally, it would be nice to have an alternative message saying that checking for updates has failed, which would help me diagnose any internet issues quicker if I am having any.

**Comment by TrainDoctor** [comment]
Definitely agree, I'll see if anyone is interested in working on this.

**Comment by zerojay** [comment]
Make it optional. Some of us prefer having fewer toast messages popping up when booting the Steam Deck and don't frustrated and hammer buttons.

**Comment by ttang4299** [comment]
> Make it optional. Some of us prefer having fewer toast messages popping up when booting the Steam Deck and don't frustrated and hammer buttons.

I agree that there should be an option to toggle it on/off, but I strongly believe it should be available given the recent occurrences of plugins breaking.

**Comment by NGnius** [comment]
I like the idea of a notification when the update check fails (both for the automatic or manual check), since it's good UX to report uncorrectable errors to the user.

On the other hand, I don't think a notification about there being no updates is useful, since opening the QAM can already tell you that. Imho a better way to communicate that the last manual check found no updates is to disable the button for manual update checks until the check has completed. This avoids the (albeit self-inflicted) issue of spamming it causing multiple redundant notifications while visually communicating when the update check is done. For automatic update checks, I don't think there's any good reason to ever notify the user that there are no updates, since it's supposed to work silently in the background.

**Comment by ttang4299** [comment]
> On the other hand, I don't think a notification about there being no updates is useful, since opening the QAM can already tell you that.

The problem is, the QAM will look the same if there are updates but the internet is being weird, or there are no updates at all. I'm obsessive about making sure I have all the latest plugin updates as soon as I open my Deck, so I would rather get a very obvious visual confirmation that everything has been updated. I guess a good compromise would be to show in the settings the last timestamp a successful update check was completed.

**Comment by ttang4299** [comment]
@TrainDoctor I've rephrased the title of this issue given the past negative reception to help clarify the intention. I do hope something like this could still be considered in the future.

**Comment by TrainDoctor** [comment]
No contributors internal or external have expressed an interest in adding this. If a contributor wishes to add such a feature I do not see a reason why it could not be implemented.
