### ISSUE TITLE
Readme Access

### ISSUE THREAD

**Issue by VioletStorm** [SteamDeckHomebrew/decky-loader#428]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

If a plugin has a readme, it can be viewed without needing to go through with a file manager.

### Further Description

When a plugin has been opened from the list, an ℹ️ button is next to the plugin name up top. When pressed, it shows the text within the readme file, URLs are hyperlinked.

**Comment by PartyWumpus** [comment]
This sounds pretty good, but I think instead of the readme, it should be possible to have multiple pages, and have translation support built in.

My current idea is: Each plugin can have a docs folder that contains several folders, each representing a page. Each folder then contains one or more markdown pages, with each one being a different language. Maybe there's a .json file somewhere that represents the order they're displayed in?

The pages are displayed with a `SidebarNavigation` component.

The displayed page name has to go into the markdown file so it can be translated. Maybe first line is the title?

If multiple pages is unreasonable then they can just put the markdown files directly into the docs folder.

If there isn't a docs folder then it can just fall back onto the readme.md.

`react-markdown` seems to do a pretty good job, so probably use that.

The multiple pages thing isn't particularly needed, but I'd quite like to include translation support in this.

When I have some free time I'll do some tinkering with getting this working, because I'd really like this (no promises though!).

**Comment by Witherking25** [comment]
~/homebrew/docs/{plugin}/{language code}/{page}.md

**Comment by Witherking25** [comment]
Or maybe 
~/homebrew/plugins/{plugin}/docs/{language code}/{page}.md

**Comment by VioletStorm** [comment]
> Or maybe 
> ~/homebrew/plugins/{plugin}/docs/{language code}/{page}.md

It'd be this yeah, and if /docs doesn't exist it would instead use /readme.md (case independent of course), or so I gather from PartyWumpus! ☺️

**Comment by PartyWumpus** [comment]
> ~/homebrew/plugins/{plugin}/docs/{language code}/{page}.md

I think this one is best, as the data is only ever going to change when the plugin updates and it reduces the file management required

**Comment by Witherking25** [comment]
Devs could set up crowdin for their repos so that people can translate the docs

**Comment by AAGaming00** [comment]
> Devs could set up crowdin for their repos so that people can translate the docs

We could also perhaps offer plugin developers space on our Weblate instance.

**Comment by Witherking25** [comment]
Does weblate support markdown?

**Comment by PartyWumpus** [comment]
> Does weblate support markdown?

Weblate does not appear to support markdown

Also, my work in progress version is now up (#432), although it will not work for now unless you manually modify it to remove the i18next depedency.

**Comment by Witherking25** [comment]
> Weblate does not appear to support markdown

Technically no, but it does support text files

**Comment by TrainDoctor** [comment]
In all likelyhood, it would be best to just have plugins explain their functionality inside of their UI and link to webpages if absolutely necessary.
