### ISSUE TITLE
[BUG] localStorage.getItem is not a function

### ISSUE THREAD

**Issue by bleonard252** [SteamDeckHomebrew/decky-loader#437]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Plugins that try to use LocalStorage throw `localStorage.getItem is not a function` errors. This only happens on the latest pre-release of Decky; the latest stable does not have this issue.

Two plugins I know of that have this issue are ProtonDB (see below) and vibrantDeck.

The only plugin I have installed that I know modifies the game detail view is ProtonDB, and it spits out the same error vibrantDeck does, while also refusing to render the page.

### Expected Behaviour

The plugins do not show this error, and the game detail pages load.

### SteamOS version

SteamOS 3.4.6 (Release Candidate channel)

### Selected Update Channel

Prerelease

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11376414/decky_logs.txt)
[steamloopback.host-1683051597591.log (JavaScript logs)](https://github.com/SteamDeckHomebrew/decky-loader/files/11376434/steamloopback.host-1683051597591.log)

**Comment by nabel0** [comment]
I also can confirm this. For example VibrantDeck trows an error now

**Comment by RodoMa92** [comment]
Tried to track it down this morning to no avail. The only thing it comes to mind that might cause this issue is the change in https://github.com/SteamDeckHomebrew/decky-loader/blob/main/frontend/rollup.config.js#L19 and that for whatever reason is eating away the localStorage definition in the plugins. I can't prove this since removing that change breaks compilation of the loader, so it's not really an option. This is just an hypothesis, though.

If someone more experienced in React/Rollup/Typescript shenanigans want to take a look, that would be very appreciated.

Marco.

**Comment by RodoMa92** [comment]
Another possibility is that since the import has been changed this will require a bump for both DFL and all plugins, haven't tested that possibility yet.

**Comment by RodoMa92** [comment]
Fixed as soon as #439 is merged.
