### ISSUE TITLE
[BUG] Plugins installed with zip or link do not show up until decky restarts

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-loader#527]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Install a plugin with zip or with link in the developer settings, it will not show up in the plugins list until decky restarts (restarting the frontend alone does *not* fix it, so it's a problem in the backend). Looking through the code, I can't really tell why this happens, as the function calls look the same. (maybe the InstallType is wrong?)

### Expected Behaviour

The plugin should appear right away.

### SteamOS version

SteamOS 3.5 Main, and my EndevourOS desktop

### Selected Update Channel

Prerelease

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/12380494/deckylog.txt)

**Comment by eXhumer** [comment]
Hello. I came across this as well when I had to install TabMaster's new update and did a bit more digging through the code to figure out the problem, it seems to be due to the code in `src/backend/browser.py` backend code, more specifically the `_install` method inside it.

First issue is when the function tries to determine if the plugin is already installed, it fails this check until the ZIP file is named exactly the same as the plugin name

https://github.com/SteamDeckHomebrew/decky-loader/blob/9295e4b038a32cbfa49ac7fffa69a3768f786491/backend/src/browser.py#L166

Any ZIP which is not named exactly as the plugin name will fail this check always and will assume the plugin is not installed already.

https://github.com/SteamDeckHomebrew/decky-loader/blob/9295e4b038a32cbfa49ac7fffa69a3768f786491/backend/src/browser.py#L111-L120

This piece of code is never executed as a result of the failed check

https://github.com/SteamDeckHomebrew/decky-loader/blob/9295e4b038a32cbfa49ac7fffa69a3768f786491/backend/src/browser.py#L206-L212

And this is the final bit of mistake. ZIP is extracted, but since the `find_plugin_folder` fails, it raises AssertionError because of an empty plugin_folder and halts the rest of the code execution.

https://github.com/SteamDeckHomebrew/decky-loader/blob/9295e4b038a32cbfa49ac7fffa69a3768f786491/backend/src/browser.py#L214-L219

**Comment by eXhumer** [comment]
This ultimately boils down to what "name" is assigned when requesting to install the plugin.

When using the plugin storefront or reinstalling it, the plugin name is provided directly from the frontend. While install from URL, it instead strips out the .zip extension from the filename and uses it as the name.

https://github.com/SteamDeckHomebrew/decky-loader/blob/9295e4b038a32cbfa49ac7fffa69a3768f786491/frontend/src/store.tsx#L73-L90

The best suggestion I have is to use fetch the ZIP and read the plugin.json directly from the ZIP to get the plugin name correctly while installing from developer mode.

**Comment by PartyWumpus** [comment]
Good job figuring that one out, thank you. 
Will be good to get this fixed.

**Comment by PartyWumpus** [comment]
This was fixed a while ago, forgot to close the issue. Thanks for this!
