### ISSUE TITLE
[BUG] Decky Loader made Life is Strange 2 Input System not working

### ISSUE THREAD

**Issue by mpeschina** [SteamDeckHomebrew/decky-loader#719]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

I installed Decky Loader (think its version 3.0.1 stable, but not sure. The main version on the day of submiting this bug) and noticed that the Inputs for the game Life is Strange 2 did not work  anymore. 

After having a chat with Steam Support, they pointed me to un-install Decky and the game worked again. 

(I have no logs and no further information. Just dropping this here, if you want to improve.. For me this is a breaking bug and I cannot use it anymore.)

### Expected Behaviour

Not kill the Input System of any game. 

### SteamOS version

3.6.19 stable

### Selected Update Channel

Stable

### Decky Loader Version

3.0.1 (not sure)

### Plugin Info

None

### Backend Logs

None

### Frontend Logs

None

**Comment by TrainDoctor** [comment]
As you stated, you have provided no logs and no specific instructions on ways to reproduce your issue. You did not list any plugins you had installed or even verify that decky was the issue through A/B testing. You also apparently did not attempt any other solutions. This issue is closed until any actual information we can use to fix this apparent "bug" that could be caused by a bug in Steam itself.
